version: '3'

services:
  db:
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=cloud
      - MYSQL_USER=php_docker
      - MYSQL_PASSWORD=password
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
    volumes:
      - "./db:/docker-entrypoint-initdb.d"

  www:
    build:
      context : .
      dockerfile: Dockerfile
    ports:
      - "80:80"  # Mapping host port 80 to container port 80
    volumes:
      - .:/var/www/html